POST http://localhost:3020/cc HTTP/1.1
Content-Type: text/turtle
Accept: text/turtle

@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix r: <http://ontology.cf.ericsson.net/reasoner/> .
@prefix v: <http://ontology.cf.ericsson.net/reasoner/variables/> .
@prefix ex: <http://example.org/> .
@prefix : <http://hybridai.org/> .

<urn:uuid:msg-bootstrap-assert> a r:Message ;
  r:to r:KnowledgeBase ;
  r:subject "assert" ;
  r:payload [
    a r:Rule ;
    r:id :notify-python-orchestrator ;
    
    r:match [ 
      r:id v:DeviationFact ;
      a :KPIDeviation ;
      :source :MiniRocket ;
      :kpiStream v:StreamId ;
      :deviationValue v:Value
    ] ;
            
    r:except [ 
      r:id v:DeviationFact ; 
      :notifiedGroundingLayer true 
    ] ;
    
    r:assert [ 
      r:id v:DeviationFact ; 
      :notifiedGroundingLayer true 
    ] ;
    
    r:prepare (
      "create_json_message" v:Payload
      ( "stream" v:StreamId 
        "value" v:Value 
        "message" "Success, this fact got updated!" )
    ) ;
    
    r:effect (
      "and"
      ( "debug" "MiniRocket deviation chained! Sending callback for " v:StreamId )
      ( "send_http_post" "http://localhost:8080/api/cc-callback" v:Payload )
    )
  ] .


###


POST http://localhost:3020/cc HTTP/1.1
Content-Type: text/turtle
Accept: text/turtle

@prefix r: <http://ontology.cf.ericsson.net/reasoner/> .
@prefix : <http://hybridai.org/ontology#> .

<urn:uuid:test-deviation-001> a r:Message ;
  r:to r:KnowledgeBase ;
  r:subject "assert" ;
  r:payload [
    a :KPIDeviation ;
    :source :MiniRocket ;
    :kpiStream "DRB_PdcpSduDelayDl" ;
    :deviationValue "45.2"
  ] .