{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "93f6de82",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'numpy'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mModuleNotFoundError\u001b[39m                       Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[1]\u001b[39m\u001b[32m, line 1\u001b[39m\n\u001b[32m----> \u001b[39m\u001b[32m1\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mnumpy\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mnp\u001b[39;00m\n\u001b[32m      3\u001b[39m W, F = \u001b[32m12\u001b[39m, \u001b[32m10\u001b[39m\n\u001b[32m      4\u001b[39m K = \u001b[32m3\u001b[39m\n",
      "\u001b[31mModuleNotFoundError\u001b[39m: No module named 'numpy'"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "\n",
    "W, F = 12, 10\n",
    "K = 3\n",
    "CELL_CAP, SLICE_CAP = 2, 2\n",
    "D = 5 + 3 + CELL_CAP + SLICE_CAP + 8  # = 20\n",
    "\n",
    "N = 5000\n",
    "data = []\n",
    "for _ in range(N):\n",
    "    sample = {\n",
    "        \"s\":  np.random.randn(W, F).astype(np.float32),\n",
    "        \"a\":  np.random.randn(K, D).astype(np.float32),\n",
    "        \"r\":  float(np.random.randn()),\n",
    "        \"s2\": np.random.randn(W, F).astype(np.float32),\n",
    "        \"done\": bool(np.random.rand() < 0.1),\n",
    "    }\n",
    "    data.append(sample)\n",
    "\n",
    "np.savez_compressed(\"replay_buffer.npz\", data=data)\n",
    "print(\"✅ dummy replay regenerated with D=\", D)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "78ba3ba0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1840938f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# set F from the demo\n",
    "from core.control_layer.RL_engines.observer_rl import RLObserver, Intent\n",
    "F = len(RLObserver(None, Intent(type=\"REDUCE_LATENCY\", metric=\"delay_p95_ms\", target=40)).features)\n",
    "print(\"Trainer F =\", F)   # should print 10 to match your demo\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0dbe1490",
   "metadata": {},
   "outputs": [],
   "source": [
    "%pip install -q torch\n",
    "\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "from core.control_layer.RL_engines.model_defs import SlateDQNetwork\n",
    "\n",
    "\n",
    "ACTION_TYPES = [\"MCS_CAP\", \"PRB_WEIGHT\", \"SLICE_QOS\", \"SCHEDULER_POLICY\", \"REPORTING\"]\n",
    "SCOPES = [\"CELL\", \"SLICE\"]\n",
    "CELLS = [\"CELL_001\", \"CELL_002\"]\n",
    "SLICES = [\"SLICE_A\", \"SLICE_B\"]\n",
    "\n",
    "\n",
    "W = 12\n",
    "F = 10         \n",
    "CELL_CAP  =  len(CELLS)   # or load from meta/replay\n",
    "SLICE_CAP =  len(SLICES)\n",
    "\n",
    "class QNet(nn.Module):\n",
    "    def __init__(self, f_dim=F, h=64):\n",
    "        super().__init__()\n",
    "        self.gru = nn.GRU(input_size=f_dim, hidden_size=h, batch_first=True)\n",
    "        self.act = nn.Sequential(\n",
    "            nn.Linear(f_dim, h), \n",
    "            nn.ReLU(),\n",
    "            nn.Linear(h, h)\n",
    "        )\n",
    "        self.head = nn.Sequential(\n",
    "            nn.Linear(2*h, h), \n",
    "            nn.ReLU(),\n",
    "            nn.Linear(h, 1)\n",
    "        )\n",
    "    def forward(self, s_win, a_vec):\n",
    "        # s_win: [B,W,F], a_vec: [B,A_DIM]\n",
    "        g, _ = self.gru(s_win)              # [B,W,H]\n",
    "        s_emb = g[:, -1, :]                 # [B,H]\n",
    "        a_emb = self.act(a_vec)             # [B,H]\n",
    "        x = torch.cat([s_emb, a_emb], dim=1)\n",
    "        return self.head(x).squeeze(1)      # [B]\n",
    "\n",
    "class Replay(Dataset):\n",
    "    def __init__(self, path):\n",
    "        buf = np.load(path, allow_pickle=True)[\"data\"]\n",
    "        self.data = buf\n",
    "    def __len__(self): return len(self.data)\n",
    "    def __getitem__(self, i):\n",
    "        t = self.data[i]   # already a dict\n",
    "        return (t[\"s\"], t[\"a\"], t[\"r\"], t[\"s2\"], float(t[\"done\"]))\n",
    "\n",
    "\n",
    "\n",
    "def td_target(qnet, s2, a_best_next, gamma=0.95):\n",
    "    with torch.no_grad():\n",
    "        q_next = qnet(s2, a_best_next)\n",
    "    return q_next * gamma\n",
    "\n",
    "# Load\n",
    "ds = Replay(\"replay_buffer.npz\")\n",
    "dl = DataLoader(ds, batch_size=256, shuffle=True, drop_last=True)\n",
    "\n",
    "net = SlateDQNetwork(feat_dim=F, cell_cap=CELL_CAP, slice_cap=SLICE_CAP)\n",
    "tgt = SlateDQNetwork(feat_dim=F, cell_cap=CELL_CAP, slice_cap=SLICE_CAP)\n",
    "tgt.load_state_dict(net.state_dict())\n",
    "opt = optim.Adam(net.parameters(), lr=1e-3)\n",
    "gamma = 0.95\n",
    "tau = 0.005\n",
    "\n",
    "for epoch in range(10):\n",
    "    for s, p, r, s2, done in dl:\n",
    "        s  = torch.tensor(s).float()\n",
    "        p  = torch.tensor(p).float()\n",
    "        s2 = torch.tensor(s2).float()\n",
    "        r  = torch.tensor(r).float()\n",
    "        done = torch.tensor(done).float()\n",
    "\n",
    "\n",
    "        q = net(s, p)\n",
    "\n",
    "        with torch.no_grad():\n",
    "            q2 = tgt(s2, p)\n",
    "            y  = r + (1.0 - done) * gamma * q2\n",
    "\n",
    "        loss = (q - y).pow(2).mean()\n",
    "        opt.zero_grad(); loss.backward(); opt.step()\n",
    "\n",
    "        with torch.no_grad():\n",
    "            for tp, p_ in zip(tgt.parameters(), net.parameters()):\n",
    "                tp.data.mul_(1 - tau).add_(tau * p_.data)\n",
    "\n",
    "\n",
    "# Save weights\n",
    "torch.save({\n",
    "    \"state_dict\": net.state_dict(),\n",
    "    \"meta\": {\"W\": W, \"F\": F, \"cell_cap\": CELL_CAP, \"slice_cap\": SLICE_CAP}\n",
    "}, \"models/qnet_offline.pt\")\n",
    "print(\"Saved mode to models/qnet_offline.pt\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "hybridai-nextg-XfHuXny8-py3.11",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
